#Aliases
alias shutn='shutdown now'
alias ls='ls --color=auto'
alias ll='ls -lah'
alias h='cd ~'
alias b='cd ..'
alias bb='cd ../..'
alias bbb='cd ../../..'
alias firefox='firefox & q'
alias q='exit'
alias c='clear'
alias rm='rm -iv'
alias mv='mv -v'
alias cp='cp -v'
alias compoff='xfconf-query -c xfwm4 -p /general/use_compositing -s false'
alias compon='xfconf-query -c xfwm4 -p /general/use_compositing -s true'
alias proton='sudo protonvpn c --cc nl'
#Keyboards
alias us='setxkmap -layout us'
alias dv='setxkmap -layout dvorak'
#Git
alias gits='git status'
alias gitdf='git diff'
alias gitc='git commit'
alias gita='git add'
alias gitp='git push'
alias gitpl='git pull'
alias gitcl='git clone'
alias gitco='git checkout'
alias gitgud='git fetch origin && git reset --hard origin/master'
